export const GET_REQUEST = "GET_REQUEST";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_FAILURE = "GET_FAILURE";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const ADD_FAILURE = "ADD_FAILURE";

export const DEL_REQUEST = "DEL_REQUEST";
export const DEL_SUCCESS = "DEL_SUCCESS";
export const DEL_FAILURE = "DEL_FAILURE";

export const PUT_REQUEST = "PUT_REQUEST";
export const PUT_SUCCESS = "PUT_SUCCESS";
export const PUT_FAILURE = "PUT_FAILURE";

export const DOWNLOAD_EXCEL_REQUEST = "DOWNLOAD_EXCEL_REQUEST";
export const DOWNLOAD_EXCEL_SUCCESS = "DOWNLOAD_EXCEL_SUCCESS";
export const DOWNLOAD_EXCEL_FAILURE = "DOWNLOAD_EXCEL_FAILURE";

export const IMPORT_EXCEL_REQUEST = "IMPORT_EXCEL_REQUEST";
export const IMPORT_EXCEL_SUCCESS = "IMPORT_EXCEL_SUCCESS";
export const IMPORT_EXCEL_FAILURE = "IMPORT_EXCEL_FAILURE";
